package org.patrick.mybatis.generator.expand.comment;

import org.mybatis.generator.api.IntrospectedColumn;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.dom.java.Field;
import org.mybatis.generator.config.PropertyRegistry;
import org.mybatis.generator.internal.DefaultCommentGenerator;
import org.mybatis.generator.internal.util.StringUtility;

import java.util.Properties;
import java.util.Scanner;

/**
 * <p></p>
 *
 * @author dl
 * @Date 2017/1/6 16:03
 */
public class CommentGenerator extends DefaultCommentGenerator {
    private boolean suppressAllComments;

    @Override
    public void addConfigurationProperties(Properties properties) {
        super.addConfigurationProperties(properties);
        this.suppressAllComments = StringUtility.isTrue(properties.getProperty(PropertyRegistry.COMMENT_GENERATOR_SUPPRESS_ALL_COMMENTS));
    }

    @Override
    public void addFieldComment(Field field, IntrospectedTable introspectedTable, IntrospectedColumn introspectedColumn) {
        if (this.suppressAllComments) {
            return;
        }
        super.addFieldComment(field, introspectedTable, introspectedColumn);
        field.addJavaDocLine("/**");
        field.addJavaDocLine(" * This field was generated by MyBatis Generator.");
        StringBuilder sb = new StringBuilder();
        sb.append(" * This field corresponds to the database column ");
        sb.append(introspectedTable.getFullyQualifiedTable());
        sb.append('.');
        sb.append(introspectedColumn.getActualColumnName());
        field.addJavaDocLine(sb.toString());
        Scanner scanner = new Scanner(introspectedColumn.getRemarks());
        while (scanner.hasNextLine()) {
            field.addJavaDocLine(new StringBuilder().append(" * ").append(scanner.nextLine()).toString());
        }
        addJavadocTag(field, false);
        field.addJavaDocLine(" */");
    }
}
